import { useRef, useState } from 'react';
import {
  Dialog, DialogTitle, DialogContent, DialogActions,
  Button, Box, Typography, Alert,
} from '@mui/material';
import { Download, Upload, Image as ImageIcon } from '@mui/icons-material';
import { toPng } from 'html-to-image';
import { useStore } from '../../store/useStore';
import type { ExportData } from '../../types';

interface ExportImportDialogProps {
  open: boolean;
  onClose: () => void;
}

export default function ExportImportDialog({ open, onClose }: ExportImportDialogProps) {
  const { points, settings, colorSlots, hydrate } = useStore();
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExportJson = () => {
    const data: ExportData = {
      version: 1,
      points,
      settings: {
        unit: settings.unit,
        themeMode: settings.themeMode,
        mapProvider: settings.mapProvider,
        satelliteView: settings.satelliteView,
        lastViewport: settings.lastViewport,
      },
      colorSlots,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `range-config-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setSuccess('Configuration exported!');
  };

  const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    setError('');
    setSuccess('');
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target?.result as string) as ExportData;
        if (!data.version || !data.points || !Array.isArray(data.points)) {
          throw new Error('Invalid config format');
        }
        // Validate each point has required fields
        for (const p of data.points) {
          if (!p.id || typeof p.lat !== 'number' || typeof p.lng !== 'number') {
            throw new Error('Invalid point data');
          }
        }
        hydrate({
          points: data.points,
          settings: data.settings ? { ...settings, ...data.settings } : undefined,
          colorSlots: data.colorSlots,
        });
        setSuccess('Configuration imported successfully!');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to parse config file');
      }
    };
    reader.readAsText(file);
    // Reset file input
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleExportImage = async (withLegend: boolean) => {
    setError('');
    try {
      const mapEl = document.querySelector('.leaflet-container') as HTMLElement;
      if (!mapEl) {
        setError('Map not found');
        return;
      }

      if (!withLegend) {
        const dataUrl = await toPng(mapEl, { quality: 0.95 });
        downloadImage(dataUrl, 'range-map.png');
        setSuccess('Map image exported!');
        return;
      }

      // With legend: create a wrapper with map + legend panel
      const wrapper = document.createElement('div');
      wrapper.style.cssText = 'display:flex; background:#fff; position:fixed; top:-9999px; left:-9999px;';

      const mapClone = mapEl.cloneNode(true) as HTMLElement;
      mapClone.style.width = `${mapEl.offsetWidth}px`;
      mapClone.style.height = `${mapEl.offsetHeight}px`;
      wrapper.appendChild(mapClone);

      const legend = document.createElement('div');
      legend.style.cssText = 'width:250px; padding:20px; font-family:sans-serif; background:#fff;';
      legend.innerHTML = `
        <h3 style="margin:0 0 16px">Range Map</h3>
        ${points.map((p) => `
          <div style="margin-bottom:12px">
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:4px">
              <div style="width:12px; height:12px; border-radius:50%; background:${p.color}"></div>
              <strong>${p.label}</strong>
            </div>
            <div style="font-size:12px; color:#666">${p.lat.toFixed(4)}, ${p.lng.toFixed(4)}</div>
            ${p.circles.map((c) => `<div style="font-size:12px; margin-left:20px">• ${c.radius.toFixed(1)} km</div>`).join('')}
          </div>
        `).join('')}
        <div style="font-size:10px; color:#999; margin-top:20px; border-top:1px solid #eee; padding-top:8px">
          Generated by Range App
        </div>
      `;
      wrapper.appendChild(legend);
      document.body.appendChild(wrapper);

      try {
        const dataUrl = await toPng(wrapper, { quality: 0.95 });
        downloadImage(dataUrl, 'range-map-legend.png');
        setSuccess('Map with legend exported!');
      } finally {
        document.body.removeChild(wrapper);
      }
    } catch (err) {
      setError('Failed to export image. Try again.');
    }
  };

  const downloadImage = (dataUrl: string, filename: string) => {
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = filename;
    a.click();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle>Export / Import</DialogTitle>
      <DialogContent>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
          <Typography variant="subtitle2">Configuration (JSON)</Typography>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Button
              variant="outlined"
              startIcon={<Download />}
              onClick={handleExportJson}
              fullWidth
            >
              Export
            </Button>
            <Button
              variant="outlined"
              startIcon={<Upload />}
              onClick={() => fileInputRef.current?.click()}
              fullWidth
            >
              Import
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept=".json"
              onChange={handleImport}
              style={{ display: 'none' }}
            />
          </Box>

          <Typography variant="subtitle2">Image Export</Typography>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Button
              variant="outlined"
              startIcon={<ImageIcon />}
              onClick={() => handleExportImage(false)}
              fullWidth
            >
              Clean
            </Button>
            <Button
              variant="outlined"
              startIcon={<ImageIcon />}
              onClick={() => handleExportImage(true)}
              fullWidth
            >
              With Legend
            </Button>
          </Box>

          {error && <Alert severity="error" onClose={() => setError('')}>{error}</Alert>}
          {success && <Alert severity="success" onClose={() => setSuccess('')}>{success}</Alert>}
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
}
